const menu = [
  {
    id: 1,
    title: 'Localisation',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe.jpg',
  },
  {
    id: 2,
    title: 'Extincteurs',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe Extincteurs.jpg',
  },
  {
    id: 3,
    title: 'Détecteurs',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 4,
    title: 'Localisation',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/item-4.jpeg',
  },
  {
    id: 5,
    title: 'Extincteurs',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/item-5.jpeg',
  },
  {
    id: 6,
    title: 'Détecteurs',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Localisation',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/item-7.jpeg',
  },
  {
    id: 8,
    title: 'Extincteurs',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/item-7.jpeg',
  },
  {
    id: 9,
    title: 'Détecteurs',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/item-7.jpeg',
  },
  {
    id: 10,
    title: 'Localisation',
    category: 'RDC',
    loc: 'RDC',
    img: '/images/item-8.jpeg',
  },
  {
    id: 11,
    title: 'Extincteurs',
    category: 'RDC',
    loc: 'RDC',
    img: '/images/item-9.jpeg',
  },
  {
    id: 12,
    title: 'Détecteurs',
    category: 'RDC',
    loc: 'RDC',

    img: '/images/Annexe Extincteurs.jpg',
  },
  {
    id: 13,
    title: 'Localisation',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 14,
    title: 'Extincteurs',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 15,
    title: 'Détecteurs',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 16,
    title: 'Localisation',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 17,
    title: 'Extincteurs',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 18,
    title: 'Détecteurs',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 19,
    title: 'Localisation',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 20,
    title: 'Extincteurs',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 21,
    title: 'Détecteurs',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/Annexe DAI.jpg',
  },
];
export default menu;
